### ISSUE TITLE
Unusual Adjacents

### ISSUE THREAD

**Issue by hal609** [Hal609/AIP_map_search#1]
When running:

```Python
self.open.extend([Node(node_id, parent=next_node) for node_id in adj_dict[next_node.node_id] if Node(node_id) not in self.closed])
```

in the search_step method there are nodes being added to the open set when do not neighbour the current node. This results in the agent jumping to non-adjacent nodes and messing up the algorithms. This is easiest to see when animating a breadth-first search and noting the odd jumping around of the highlighted red node.

**Comment by Hal609** [comment]
Turns out this was a visual bug in update_graph_visuals causing the wrong nodes to be highlighted.

**Comment by hal609** [comment]
Turns out this was a visual bug in update_graph_visuals causing the wrong nodes to be highlighted.
